# Generated by Django 2.0.9 on 2019-04-01 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '测试1',
                'verbose_name_plural': '测试1',
            },
        ),
    ]
